#!/bin/bash

set -eux -o pipefail

CWD="$(pwd)"
ln -nsf "$CWD" "$HOME/.config/nvim"

VERSION="0.12.5"
TARBALL="nvim-linux-x86_64.tar.gz"
URL="https://github.com/neovim/neovim/releases/download/v${VERSION}/${TARBALL}"
HASH="bce0f56eda1f1b1db6eee8f4133d7a38813ea07933837dd1777411ca384c6875"

if ! [ -e ~/.cache/nvim-download-$VERSION ]
then
    pushd /tmp
    rm -f "$TARBALL"
    wget "$URL"
    echo "$HASH  $TARBALL" | sha256sum -c
    tar -xzf "$TARBALL"
    rm -rf "$HOME/.local/share/nvim"
    mv nvim-linux-x86_64 "$HOME/.local/share/nvim"
    ln -nsf "$HOME/.local/share/nvim/bin/nvim" "$HOME/.local/bin/nvim"
    touch ~/.cache/nvim-download-$VERSION
fi
