#!/bin/bash

set -eux -o pipefail

CWD="$(pwd)"
ln -nsf "$CWD" "$HOME/.config/nvim"

# neovim
VERSION="0.12.5"
TARBALL="nvim-linux-x86_64.tar.gz"
URL="https://github.com/neovim/neovim/releases/download/v${VERSION}/${TARBALL}"
HASH="bce0f56eda1f1b1db6eee8f4133d7a38813ea07933837dd1777411ca384c6875"

if ! [ -e ~/.cache/nvim-download-$VERSION ]
then
    pushd /tmp
    rm -f "$TARBALL"
    wget "$URL"
    echo "$HASH  $TARBALL" | sha256sum -c
    tar -xzf "$TARBALL"
    rm -rf "$HOME/.local/share/nvim"
    mv nvim-linux-x86_64 "$HOME/.local/share/nvim"
    ln -nsf "$HOME/.local/share/nvim/bin/nvim" "$HOME/.local/bin/nvim"
    rm -f ~/.cache/nvim-download-*
    touch ~/.cache/nvim-download-$VERSION
fi

# tree-sitter
VERSION="0.27.0"
TARBALL="tree-sitter-linux-x64.gz"
URL="https://github.com/tree-sitter/tree-sitter/releases/download/v${VERSION}/${TARBALL}"
HASH="20a1f39ec1c45f2211492dcb8881c802b643b554bb196869a29ac3778277fa77"

if ! [ -e ~/.cache/tree-sitter-$VERSION ]
then
    pushd /tmp
    rm -f "$TARBALL"
    wget "$URL"
    echo "$HASH  $TARBALL" | sha256sum -c
    gunzip "$TARBALL"
    chmod +x tree-sitter-linux-x64
    mv tree-sitter-linux-x64 "$HOME/.local/bin/tree-sitter"
    rm -f ~/.cache/tree-sitter--*
    touch ~/.cache/tree-sitter--$VERSION
fi

# vhdl-ls
VERSION="0.88.0"
TARBALL="vhdl_ls-x86_64-unknown-linux-musl.zip"
URL="https://github.com/VHDL-LS/rust_hdl/releases/download/v${VERSION}/${TARBALL}"
HASH="5cb90333e5f93e11d83d4f980b7c7ff204b11283c854efcafe2ff0b5cf41f7ec"

if ! [ -e ~/.cache/vhdl-ls-$VERSION ]
then
    pushd /tmp
    rm -f "$TARBALL"
    wget "$URL"
    echo "$HASH  $TARBALL" | sha256sum -c
    unzip "$TARBALL"
    rm -rf "$HOME/.local/share/vhdl-ls/*"
    mv vhdl_ls-x86_64-unknown-linux-musl "$HOME/.local/share/vhdl-ls/"
    ln -nsf "$HOME/.local/share/vhdl-ls/bin/vhdl_ls" "$HOME/.local/bin/vhdl_ls"
    rm -f ~/.cache/vhdl-ls--*
    touch ~/.cache/vhdl-ls--$VERSION
fi
